// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKlZ-Y5du9f0cLAuF2RlUblrQqhKRfJck',
    appId: '1:783901102151:web:6916124cb30287573be162',
    messagingSenderId: '783901102151',
    projectId: 'delivery-b9e82',
    authDomain: 'delivery-b9e82.firebaseapp.com',
    storageBucket: 'delivery-b9e82.firebasestorage.app',
    measurementId: 'G-B447F47HHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdCzyGkZb3odB175juoWM-ZK-xGUVcuYU',
    appId: '1:783901102151:android:394e4b0d6eecf83e3be162',
    messagingSenderId: '783901102151',
    projectId: 'delivery-b9e82',
    storageBucket: 'delivery-b9e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYoettlKOMBJrXBBMmSZlM5GGQCZ9ukc',
    appId: '1:783901102151:ios:a54895bee33e0f713be162',
    messagingSenderId: '783901102151',
    projectId: 'delivery-b9e82',
    storageBucket: 'delivery-b9e82.firebasestorage.app',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKlZ-Y5du9f0cLAuF2RlUblrQqhKRfJck',
    appId: '1:783901102151:web:667c80174d9659f23be162',
    messagingSenderId: '783901102151',
    projectId: 'delivery-b9e82',
    authDomain: 'delivery-b9e82.firebaseapp.com',
    storageBucket: 'delivery-b9e82.firebasestorage.app',
    measurementId: 'G-CS713R3K6M',
  );
}
